### ISSUE TITLE
Como usar esta api en el sitio web de Pixelesp?

### ISSUE THREAD

**Issue by ariadnaguitian** [ariadnaguitian/api-#1]
Hola profesor, estamos intentando vincular la api al sitio web y no sabemos bien como hacerlo, como puede ser? Muchas gracias!

**Comment by catrielmuller** [comment]
Ariadna, Disculpa las demoras en contestar, estuve baste complicado la semana pasada con cuestiones personales.

Primero tienen que entender este concepto para ver la diferencia con lo que tienen actualmente.
https://es.wikipedia.org/wiki/Single-page_application

Para usar la API pueden implementar algún framework como AngularJS ( https://angularjs.org/ ) u Ionic como en la APP, que los va a forzar a usar el patrón SPA.

Tienen un hermoso curso gratuito aqui: http://campus.codeschool.com/courses/shaping-up-with-angular-js/intro

Ionic usa Angular, por lo que la estructura no les debería resultar extraña.

También puede simplemente hacer llamadas GET, POST, etc usando Javascript como vieron en Programación 3.
